### ISSUE TITLE
Better support for build caches

### ISSUE THREAD

**Issue by rlupton20** [Metaswitch/floki#35]
Some build tools like to persist build data to disk. It would be nice if `floki` allowed build caches created inside the container to persist between container launches, and even across containers in different which might want to share a cache (e.g. Rust builds).

Caches should work even if the user hasn't configured them (as in, they should do something sensible if enabled, and not rely on the users environment), but it may be worthwhile allowing users to set a particular file directory for a cache.

**Comment by rlupton20** [comment]
Currently proposing a new YAML field as below:

```
volumes:
  key:  # only used if the volume is shared, otherwise, just a useful piece of documentation
    shared: false  # optional, defaulting to false
    mount: /path/to/mount/inside/container
```

Folders will be created in `~/.floki/volumes` as needed, using a name unique to the base directory, unless the volume is shared. An extension can then be made to allow `floki` to use shared volumes with configurable path, along with suitable CLI backing to make it configurable. Something like:

```
floki volume rust --set $CARGO_HOME
```

This gives the following steps:

[] Provide basic volume support in `floki`.
[] Allow shared volumes to have configurable host paths, set in a file
[] Provide additional command line control over cache paths
