### ISSUE TITLE
Better ergonomics for aliases

### ISSUE THREAD

**Issue by rlupton20** [Metaswitch/floki#68]
It would be nice to have a more ergonomic way to configure shell aliases. Maybe something like

```
aliases:
  - name: build
    command: make
  - name: clean
  - command: make clean
```
